package entidade;

import org.springframework.stereotype.Component;

/**
 * Cidade generated by hbm2java
 */
@Component
public class CidadeEntity extends Cidade implements java.io.Serializable {

	public CidadeEntity() {	}

	public CidadeEntity(Estado estado, String nmCidade) {
		super.setEstado( estado );
		super.setNmCidade( nmCidade );
	}
}