package entidade;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.springframework.beans.factory.annotation.Autowired;

/**
 * Cidade generated by hbm2java
 */
@Entity
@Table(name = "cidade", catalog = "aplicacoes")
public class Cidade implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID_CIDADE", unique = true, nullable = false)
	private Long idCidade;
	
	@Autowired
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CD_ESTADO", nullable = false)
	private Estado estado;
	
	@Column(name = "NM_CIDADE", nullable = false, length = 45)
	private String nmCidade;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cidade")
	private Set<Endereco> enderecos = new HashSet<Endereco>(0);

	public Cidade() {
	}

	public Cidade(Estado estado, String nmCidade) {
		this.estado = estado;
		this.nmCidade = nmCidade;
	}

	public Cidade(Estado estado, String nmCidade, Set<Endereco> enderecos) {
		this.estado = estado;
		this.nmCidade = nmCidade;
		this.enderecos = enderecos;
	}

	public Long getIdCidade() {
		return this.idCidade;
	}

	public void setIdCidade(Long idCidade) {
		this.idCidade = idCidade;
	}

	public Estado getEstado() {
		return this.estado;
	}

	public void setEstado(Estado estado) {
		this.estado = estado;
	}

	public String getNmCidade() {
		return this.nmCidade;
	}

	public void setNmCidade(String nmCidade) {
		this.nmCidade = nmCidade;
	}

	public Set<Endereco> getEnderecos() {
		return this.enderecos;
	}

	public void setEnderecos(Set<Endereco> enderecos) {
		this.enderecos = enderecos;
	}
}