package entidade;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Endereco generated by hbm2java
 */
@Entity
@Table(name = "endereco", catalog = "aplicacoes")
public class Endereco implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID_ENDERECO", unique = true, nullable = false)
	private Long idEndereco;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CD_LOGRADOURO", nullable = false)
	private Logradouro logradouro;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CD_CIDADE", nullable = false)
	private Cidade cidade;
	
	@Column(name = "DS_ENDERECO", nullable = false, length = 45)
	private String dsEndereco;
	
	@Column(name = "DS_NUMERO", nullable = false, length = 10)
	private String dsNumero;
	
	@Column(name = "DS_COMPLEMENTO", length = 20)
	private String dsComplemento;
	
	@Column(name = "DS_REFERENCIA", length = 45)
	private String dsReferencia;
	
	@Column(name = "DS_BAIRRO", nullable = false, length = 20)
	private String dsBairro;
	
	@Column(name = "NU_CEP", nullable = false)
	private int nuCep;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "endereco")
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public Endereco() {
	}

	public Endereco(Logradouro logradouro, Cidade cidade, String dsEndereco,
			String dsNumero, String dsBairro, int nuCep) {
		this.logradouro = logradouro;
		this.cidade = cidade;
		this.dsEndereco = dsEndereco;
		this.dsNumero = dsNumero;
		this.dsBairro = dsBairro;
		this.nuCep = nuCep;
	}

	public Endereco(Logradouro logradouro, Cidade cidade, String dsEndereco,
			String dsNumero, String dsComplemento, String dsReferencia,
			String dsBairro, int nuCep, Set<Usuario> usuarios) {
		this.logradouro = logradouro;
		this.cidade = cidade;
		this.dsEndereco = dsEndereco;
		this.dsNumero = dsNumero;
		this.dsComplemento = dsComplemento;
		this.dsReferencia = dsReferencia;
		this.dsBairro = dsBairro;
		this.nuCep = nuCep;
		this.usuarios = usuarios;
	}

	public Long getIdEndereco() {
		return this.idEndereco;
	}

	public void setIdEndereco(Long idEndereco) {
		this.idEndereco = idEndereco;
	}

	public Logradouro getLogradouro() {
		return this.logradouro;
	}

	public void setLogradouro(Logradouro logradouro) {
		this.logradouro = logradouro;
	}

	public Cidade getCidade() {
		return this.cidade;
	}

	public void setCidade(Cidade cidade) {
		this.cidade = cidade;
	}

	public String getDsEndereco() {
		return this.dsEndereco;
	}

	public void setDsEndereco(String dsEndereco) {
		this.dsEndereco = dsEndereco;
	}

	public String getDsNumero() {
		return this.dsNumero;
	}

	public void setDsNumero(String dsNumero) {
		this.dsNumero = dsNumero;
	}

	public String getDsComplemento() {
		return this.dsComplemento;
	}

	public void setDsComplemento(String dsComplemento) {
		this.dsComplemento = dsComplemento;
	}

	public String getDsReferencia() {
		return this.dsReferencia;
	}

	public void setDsReferencia(String dsReferencia) {
		this.dsReferencia = dsReferencia;
	}
	
	public String getDsBairro() {
		return this.dsBairro;
	}

	public void setDsBairro(String dsBairro) {
		this.dsBairro = dsBairro;
	}

	public int getNuCep() {
		return this.nuCep;
	}

	public void setNuCep(int nuCep) {
		this.nuCep = nuCep;
	}

	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}
}