package entidade;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estado generated by hbm2java
 */
@Entity
@Table(name = "estado", catalog = "aplicacoes")
public class Estado implements java.io.Serializable {

	private Integer idEstado;
	private String sgEstado;
	private String nmEstado;
	private String nmCapital;
	private String nmRegiao;
	private Set<Cidade> cidades = new HashSet<Cidade>(0);

	public Estado() {
	}

	public Estado(String sgEstado, String nmEstado, String nmCapital,
			String nmRegiao) {
		this.sgEstado = sgEstado;
		this.nmEstado = nmEstado;
		this.nmCapital = nmCapital;
		this.nmRegiao = nmRegiao;
	}

	public Estado(String sgEstado, String nmEstado, String nmCapital,
			String nmRegiao, Set<Cidade> cidades) {
		this.sgEstado = sgEstado;
		this.nmEstado = nmEstado;
		this.nmCapital = nmCapital;
		this.nmRegiao = nmRegiao;
		this.cidades = cidades;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID_ESTADO", unique = true, nullable = false)
	public Integer getIdEstado() {
		return this.idEstado;
	}

	public void setIdEstado(Integer idEstado) {
		this.idEstado = idEstado;
	}

	@Column(name = "SG_ESTADO", nullable = false, length = 2)
	public String getSgEstado() {
		return this.sgEstado;
	}

	public void setSgEstado(String sgEstado) {
		this.sgEstado = sgEstado;
	}

	@Column(name = "NM_ESTADO", nullable = false, length = 20)
	public String getNmEstado() {
		return this.nmEstado;
	}

	public void setNmEstado(String nmEstado) {
		this.nmEstado = nmEstado;
	}

	@Column(name = "NM_CAPITAL", nullable = false, length = 20)
	public String getNmCapital() {
		return this.nmCapital;
	}

	public void setNmCapital(String nmCapital) {
		this.nmCapital = nmCapital;
	}

	@Column(name = "NM_REGIAO", nullable = false, length = 20)
	public String getNmRegiao() {
		return this.nmRegiao;
	}

	public void setNmRegiao(String nmRegiao) {
		this.nmRegiao = nmRegiao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estado")
	public Set<Cidade> getCidades() {
		return this.cidades;
	}

	public void setCidades(Set<Cidade> cidades) {
		this.cidades = cidades;
	}

}
