package entidade;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Logradouro generated by hbm2java
 */
@Entity
@Table(name = "logradouro", catalog = "aplicacoes")
public class Logradouro implements java.io.Serializable {

	private Integer idLogradouro;
	private String nmLogradouro;
	private String sgLogradouro;
	private Set<Endereco> enderecos = new HashSet<Endereco>(0);

	public Logradouro() {
	}

	public Logradouro(String nmLogradouro, String sgLogradouro) {
		this.nmLogradouro = nmLogradouro;
		this.sgLogradouro = sgLogradouro;
	}

	public Logradouro(String nmLogradouro, String sgLogradouro,
			Set<Endereco> enderecos) {
		this.nmLogradouro = nmLogradouro;
		this.sgLogradouro = sgLogradouro;
		this.enderecos = enderecos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID_LOGRADOURO", unique = true, nullable = false)
	public Integer getIdLogradouro() {
		return this.idLogradouro;
	}

	public void setIdLogradouro(Integer idLogradouro) {
		this.idLogradouro = idLogradouro;
	}

	@Column(name = "NM_LOGRADOURO", nullable = false, length = 20)
	public String getNmLogradouro() {
		return this.nmLogradouro;
	}

	public void setNmLogradouro(String nmLogradouro) {
		this.nmLogradouro = nmLogradouro;
	}

	@Column(name = "SG_LOGRADOURO", nullable = false, length = 5)
	public String getSgLogradouro() {
		return this.sgLogradouro;
	}

	public void setSgLogradouro(String sgLogradouro) {
		this.sgLogradouro = sgLogradouro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "logradouro")
	public Set<Endereco> getEnderecos() {
		return this.enderecos;
	}

	public void setEnderecos(Set<Endereco> enderecos) {
		this.enderecos = enderecos;
	}

}
