package entidade;

import org.springframework.stereotype.Component;

/**
 * Logradouro generated by hbm2java
 */
@Component
public class LogradouroEntity extends Logradouro implements java.io.Serializable {

	@Override
	public String toString() {
		return super.getNmLogradouro();
	}

	public LogradouroEntity() {	}

	public LogradouroEntity(String nmLogradouro, String sgLogradouro) {
		super.setNmLogradouro( nmLogradouro );
		super.setSgLogradouro( sgLogradouro );
	}
}
