package entidade;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.springframework.beans.factory.annotation.Autowired;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "aplicacoes")
public class Usuario implements java.io.Serializable {

	private Integer idUsuario;
	
	@Autowired
	private Endereco endereco;
	private int cdUsuario;
	private String nmUsuario;
	private String dsLogin;
	private int nuSenha;

	public Usuario() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID_USUARIO", unique = true, nullable = false)
	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CD_ENDERECO", nullable = false)
	public Endereco getEndereco() {
		return this.endereco;
	}

	public void setEndereco(Endereco endereco) {
		this.endereco = endereco;
	}

	@Column(name = "CD_USUARIO", nullable = false)
	public int getCdUsuario() {
		return this.cdUsuario;
	}

	public void setCdUsuario(int cdUsuario) {
		this.cdUsuario = cdUsuario;
	}

	@Column(name = "NM_USUARIO", nullable = false, length = 45)
	public String getNmUsuario() {
		return this.nmUsuario;
	}

	public void setNmUsuario(String nmUsuario) {
		this.nmUsuario = nmUsuario;
	}

	@Column(name = "DS_LOGIN", nullable = false, length = 15)
	public String getDsLogin() {
		return this.dsLogin;
	}

	public void setDsLogin(String dsLogin) {
		this.dsLogin = dsLogin;
	}

	@Column(name = "NU_SENHA", nullable = false)
	public int getNuSenha() {
		return this.nuSenha;
	}

	public void setNuSenha(int nuSenha) {
		this.nuSenha = nuSenha;
	}
}