package entidade;

import org.springframework.stereotype.Component;

/**
 * Usuario generated by hbm2java
 */
@Component("usuarioEntity")
public class UsuarioEntity extends Usuario {

	public UsuarioEntity() {}

	public UsuarioEntity(Endereco endereco, int cdUsuario, String nmUsuario,
			String dsLogin, int nuSenha) {
		super.setEndereco( endereco );
		super.setCdUsuario( cdUsuario );
		super.setNmUsuario( nmUsuario );
		super.setDsLogin( dsLogin );
		super.setNuSenha( nuSenha );
	}
}
