package entidade;
import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Valores generated by hbm2java
 */
@Entity
@Table(name = "valores", catalog = "aplicacoes")
public class Valores implements java.io.Serializable {

	private Long idValores;
	private BigDecimal nuValor;
	private int tpValor;
	private int tpPeriodo;

	public Valores() {
	}

	public Valores(int tpValor, int tpPeriodo) {
		this.tpValor = tpValor;
		this.tpPeriodo = tpPeriodo;
	}

	public Valores(BigDecimal nuValor, int tpValor, int tpPeriodo) {
		this.nuValor = nuValor;
		this.tpValor = tpValor;
		this.tpPeriodo = tpPeriodo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID_VALORES", unique = true, nullable = false)
	public Long getIdValores() {
		return this.idValores;
	}

	public void setIdValores(Long idValores) {
		this.idValores = idValores;
	}

	@Column(name = "NU_VALOR", precision = 9, scale = 6)
	public BigDecimal getNuValor() {
		return this.nuValor;
	}

	public void setNuValor(BigDecimal nuValor) {
		this.nuValor = nuValor;
	}

	@Column(name = "TP_VALOR", nullable = false)
	public int getTpValor() {
		return this.tpValor;
	}

	public void setTpValor(int tpValor) {
		this.tpValor = tpValor;
	}

	@Column(name = "TP_PERIODO", nullable = false)
	public int getTpPeriodo() {
		return this.tpPeriodo;
	}

	public void setTpPeriodo(int tpPeriodo) {
		this.tpPeriodo = tpPeriodo;
	}

}
